<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) NPEU 2019.
 * @license     MIT License; see LICENSE.md
 */

defined('_JEXEC') or die;

use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Associations as LanguageAssociations;
use Joomla\CMS\Router\Route;
use Joomla\Component\Fields\Administrator\Helper\FieldsHelper;

use NPEU\Template\Npeu6\Site\Helper\Npeu6Helper as TplNPEU6Helper;


$page_brand = TplNPEU6Helper::get_brand();
$theme = 't-' . $page_brand->alias;


// Create a shortcut for params.
$params = $this->item->params;


HTMLHelper::addIncludePath(JPATH_COMPONENT . '/helpers/html');
$canEdit = $this->item->params->get('access-edit');
$info    = $params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (LanguageAssociations::isEnabled() && $params->get('show_associations'));

// Maybe need to make this configurable?
$date_format = 'd M Y';

// Get the custom fields for the article:
$fields = FieldsHelper::getFields('com_content.article', $this->item, true);
$headline_image = [];
foreach ($fields as $field) {
    switch ($field->name) {
        case 'headline-image':
            $headline_image['headline-image'] = $field->rawvalue;
            break;
        case 'headline-image-alt-text':
            $headline_image['headline-image-alt-text'] = $field->rawvalue;
            break;
        case 'headline-image-caption':
            $headline_image['headline-image-caption'] = $field->rawvalue;
            break;
        case 'headline-image-credit-line':
            $headline_image['headline-image-credit-line'] = $field->rawvalue;
            break;
    }
}

/*
// OK, so generated article stubs don't explicitly record their progenitor, but the URL field does
// record the generated link to the originating article. Since the URL field isn't used for anything
// else (and is in fact disabled for display to users, it's _reasonable_ safe to assume that if the
// `url_a` property is not empty, this article is a stub, so lets get the id of that article so we
// can then in turn get the data for that article, and use it to set things like headline images
// for _this_ article if they haven't been locally specified:
$urls = $this->item->urls;
if (!empty($urls)) {
    $urls = json_decode($urls);

    if (!empty($urls->urla)) {
        preg_match('#npeu.ox.ac.uk/news/(\d+)-.*#', $urls->urla, $matches);

        if (!empty($matches[1])) {
            // Pretty certain this is the ID of the progenitor article, so lets get that data:

            $progenitor_article = JTable::getInstance("content");
            $progenitor_article->load($matches[1]);

            JLoader::register('FieldsHelper', JPATH_ADMINISTRATOR . '/components/com_fields/helpers/fields.php'); //load fields helper
            $customFieldnames = FieldsHelper::getFields('com_content.article', $matches[1], true); // get custom field names by article id
            $customFieldIds = array_column($customFieldnames, 'id');
            $model = JModelLegacy::getInstance('Field', 'FieldsModel', array('ignore_request' => true)); //load fields model
            $customFieldValues = $model->getFieldValues($customFieldIds, $matches[1]); //Fetch values for custom field Ids

            // If the headline images URL for this article is empty, and the progenitor has one,
            // use that:
            if (empty($headline_image['headline-image']) && !empty($customFieldValues[1])) {
                $headline_image['headline-image'] = $customFieldValues[1];

                if (!empty($customFieldValues[2])) {
                    $headline_image['headline-image-alt-text'] = $customFieldValues[2];
                }

                if (!empty($customFieldValues[3])) {
                    $headline_image['headline-image-caption'] = $customFieldValues[3];
                }

                if (!empty($customFieldValues[4])) {
                    $headline_image['headline-image-credit-line'] = $customFieldValues[4];
                }
            }
        }
    }
}
*/


?>

<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
<?php #echo $this->item->event->afterDisplayTitle; ?>

<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
<?php #echo $this->item->event->beforeDisplayContent; ?>

            <div class="c-listing c-listing--no-separator c-listing--very-wide-image">
                <div class="c-listing__body">
                    <h2 class="c-listing__title">
                        <a href="<?php echo JRoute::_(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)); ?>"><span><?php echo $this->item->title; ?></span></a>
                    </h2>
                </div>

                <div class="c-listing__image">
                    <div class="u-image-cover u-image-cover--min-56-25">
                        <p class="u-image-cover__inner">
                            <img src="<?php echo $headline_image['headline-image']; ?>?s=600"" alt="<?php echo $headline_image['headline-image-alt-text']; ?>" class="u-image-cover__image" width="200" height="133">
                        </p>
                    </div>
                </div>
            </div>

            <hr />


<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
<?php echo #$this->item->event->afterDisplayContent; ?>